version: '2.0'

services:

### Apache HTTP Container ###

    apache:
        build: ./
        container_name: apache-php5
        volumes:
            - ../:/var/www/site
            - ./logs/apache/:/var/log/apache2
        ports:
            - "80:80"
            - "443:443"
